# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jouni/devel/xdev/adftools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jouni/devel/xdev/adftools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jouni/devel/xdev/adftools/CMakeFiles /Users/jouni/devel/xdev/adftools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jouni/devel/xdev/adftools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named adflist

# Build rule for target.
adflist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adflist
.PHONY : adflist

# fast build rule for target.
adflist/fast:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/build
.PHONY : adflist/fast

#=============================================================================
# Target rules for targets named adfinfo

# Build rule for target.
adfinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adfinfo
.PHONY : adfinfo

# fast build rule for target.
adfinfo/fast:
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/build
.PHONY : adfinfo/fast

#=============================================================================
# Target rules for targets named adfdump

# Build rule for target.
adfdump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adfdump
.PHONY : adfdump

# fast build rule for target.
adfdump/fast:
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/build
.PHONY : adfdump/fast

#=============================================================================
# Target rules for targets named adfcreate

# Build rule for target.
adfcreate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adfcreate
.PHONY : adfcreate

# fast build rule for target.
adfcreate/fast:
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/build
.PHONY : adfcreate/fast

#=============================================================================
# Target rules for targets named adfmakedir

# Build rule for target.
adfmakedir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adfmakedir
.PHONY : adfmakedir

# fast build rule for target.
adfmakedir/fast:
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/build
.PHONY : adfmakedir/fast

#=============================================================================
# Target rules for targets named adfextract

# Build rule for target.
adfextract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adfextract
.PHONY : adfextract

# fast build rule for target.
adfextract/fast:
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/build
.PHONY : adfextract/fast

#=============================================================================
# Target rules for targets named adfcopy

# Build rule for target.
adfcopy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adfcopy
.PHONY : adfcopy

# fast build rule for target.
adfcopy/fast:
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/build
.PHONY : adfcopy/fast

#=============================================================================
# Target rules for targets named adfdelete

# Build rule for target.
adfdelete: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adfdelete
.PHONY : adfdelete

# fast build rule for target.
adfdelete/fast:
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/build
.PHONY : adfdelete/fast

#=============================================================================
# Target rules for targets named adfinstall

# Build rule for target.
adfinstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adfinstall
.PHONY : adfinstall

# fast build rule for target.
adfinstall/fast:
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/build
.PHONY : adfinstall/fast

#=============================================================================
# Target rules for targets named adf

# Build rule for target.
adf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adf
.PHONY : adf

# fast build rule for target.
adf/fast:
	$(MAKE) -f adflib/CMakeFiles/adf.dir/build.make adflib/CMakeFiles/adf.dir/build
.PHONY : adf/fast

adfcopy.o: adfcopy.c.o

.PHONY : adfcopy.o

# target to build an object file
adfcopy.c.o:
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/adfcopy.c.o
.PHONY : adfcopy.c.o

adfcopy.i: adfcopy.c.i

.PHONY : adfcopy.i

# target to preprocess a source file
adfcopy.c.i:
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/adfcopy.c.i
.PHONY : adfcopy.c.i

adfcopy.s: adfcopy.c.s

.PHONY : adfcopy.s

# target to generate assembly for a file
adfcopy.c.s:
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/adfcopy.c.s
.PHONY : adfcopy.c.s

adfcreate.o: adfcreate.c.o

.PHONY : adfcreate.o

# target to build an object file
adfcreate.c.o:
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/adfcreate.c.o
.PHONY : adfcreate.c.o

adfcreate.i: adfcreate.c.i

.PHONY : adfcreate.i

# target to preprocess a source file
adfcreate.c.i:
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/adfcreate.c.i
.PHONY : adfcreate.c.i

adfcreate.s: adfcreate.c.s

.PHONY : adfcreate.s

# target to generate assembly for a file
adfcreate.c.s:
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/adfcreate.c.s
.PHONY : adfcreate.c.s

adfdelete.o: adfdelete.c.o

.PHONY : adfdelete.o

# target to build an object file
adfdelete.c.o:
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/adfdelete.c.o
.PHONY : adfdelete.c.o

adfdelete.i: adfdelete.c.i

.PHONY : adfdelete.i

# target to preprocess a source file
adfdelete.c.i:
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/adfdelete.c.i
.PHONY : adfdelete.c.i

adfdelete.s: adfdelete.c.s

.PHONY : adfdelete.s

# target to generate assembly for a file
adfdelete.c.s:
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/adfdelete.c.s
.PHONY : adfdelete.c.s

adfdump.o: adfdump.c.o

.PHONY : adfdump.o

# target to build an object file
adfdump.c.o:
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/adfdump.c.o
.PHONY : adfdump.c.o

adfdump.i: adfdump.c.i

.PHONY : adfdump.i

# target to preprocess a source file
adfdump.c.i:
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/adfdump.c.i
.PHONY : adfdump.c.i

adfdump.s: adfdump.c.s

.PHONY : adfdump.s

# target to generate assembly for a file
adfdump.c.s:
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/adfdump.c.s
.PHONY : adfdump.c.s

adfextract.o: adfextract.c.o

.PHONY : adfextract.o

# target to build an object file
adfextract.c.o:
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/adfextract.c.o
.PHONY : adfextract.c.o

adfextract.i: adfextract.c.i

.PHONY : adfextract.i

# target to preprocess a source file
adfextract.c.i:
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/adfextract.c.i
.PHONY : adfextract.c.i

adfextract.s: adfextract.c.s

.PHONY : adfextract.s

# target to generate assembly for a file
adfextract.c.s:
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/adfextract.c.s
.PHONY : adfextract.c.s

adfinfo.o: adfinfo.c.o

.PHONY : adfinfo.o

# target to build an object file
adfinfo.c.o:
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/adfinfo.c.o
.PHONY : adfinfo.c.o

adfinfo.i: adfinfo.c.i

.PHONY : adfinfo.i

# target to preprocess a source file
adfinfo.c.i:
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/adfinfo.c.i
.PHONY : adfinfo.c.i

adfinfo.s: adfinfo.c.s

.PHONY : adfinfo.s

# target to generate assembly for a file
adfinfo.c.s:
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/adfinfo.c.s
.PHONY : adfinfo.c.s

adfinstall.o: adfinstall.c.o

.PHONY : adfinstall.o

# target to build an object file
adfinstall.c.o:
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/adfinstall.c.o
.PHONY : adfinstall.c.o

adfinstall.i: adfinstall.c.i

.PHONY : adfinstall.i

# target to preprocess a source file
adfinstall.c.i:
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/adfinstall.c.i
.PHONY : adfinstall.c.i

adfinstall.s: adfinstall.c.s

.PHONY : adfinstall.s

# target to generate assembly for a file
adfinstall.c.s:
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/adfinstall.c.s
.PHONY : adfinstall.c.s

adflist.o: adflist.c.o

.PHONY : adflist.o

# target to build an object file
adflist.c.o:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/adflist.c.o
.PHONY : adflist.c.o

adflist.i: adflist.c.i

.PHONY : adflist.i

# target to preprocess a source file
adflist.c.i:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/adflist.c.i
.PHONY : adflist.c.i

adflist.s: adflist.c.s

.PHONY : adflist.s

# target to generate assembly for a file
adflist.c.s:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/adflist.c.s
.PHONY : adflist.c.s

adfmakedir.o: adfmakedir.c.o

.PHONY : adfmakedir.o

# target to build an object file
adfmakedir.c.o:
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/adfmakedir.c.o
.PHONY : adfmakedir.c.o

adfmakedir.i: adfmakedir.c.i

.PHONY : adfmakedir.i

# target to preprocess a source file
adfmakedir.c.i:
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/adfmakedir.c.i
.PHONY : adfmakedir.c.i

adfmakedir.s: adfmakedir.c.s

.PHONY : adfmakedir.s

# target to generate assembly for a file
adfmakedir.c.s:
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/adfmakedir.c.s
.PHONY : adfmakedir.c.s

bootblocks.o: bootblocks.c.o

.PHONY : bootblocks.o

# target to build an object file
bootblocks.c.o:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/bootblocks.c.o
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/bootblocks.c.o
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/bootblocks.c.o
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/bootblocks.c.o
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/bootblocks.c.o
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/bootblocks.c.o
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/bootblocks.c.o
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/bootblocks.c.o
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/bootblocks.c.o
.PHONY : bootblocks.c.o

bootblocks.i: bootblocks.c.i

.PHONY : bootblocks.i

# target to preprocess a source file
bootblocks.c.i:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/bootblocks.c.i
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/bootblocks.c.i
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/bootblocks.c.i
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/bootblocks.c.i
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/bootblocks.c.i
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/bootblocks.c.i
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/bootblocks.c.i
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/bootblocks.c.i
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/bootblocks.c.i
.PHONY : bootblocks.c.i

bootblocks.s: bootblocks.c.s

.PHONY : bootblocks.s

# target to generate assembly for a file
bootblocks.c.s:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/bootblocks.c.s
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/bootblocks.c.s
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/bootblocks.c.s
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/bootblocks.c.s
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/bootblocks.c.s
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/bootblocks.c.s
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/bootblocks.c.s
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/bootblocks.c.s
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/bootblocks.c.s
.PHONY : bootblocks.c.s

error.o: error.c.o

.PHONY : error.o

# target to build an object file
error.c.o:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/error.c.o
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/error.c.o
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/error.c.o
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/error.c.o
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/error.c.o
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/error.c.o
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/error.c.o
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/error.c.o
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/error.c.o
.PHONY : error.c.o

error.i: error.c.i

.PHONY : error.i

# target to preprocess a source file
error.c.i:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/error.c.i
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/error.c.i
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/error.c.i
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/error.c.i
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/error.c.i
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/error.c.i
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/error.c.i
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/error.c.i
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/error.c.i
.PHONY : error.c.i

error.s: error.c.s

.PHONY : error.s

# target to generate assembly for a file
error.c.s:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/error.c.s
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/error.c.s
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/error.c.s
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/error.c.s
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/error.c.s
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/error.c.s
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/error.c.s
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/error.c.s
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/error.c.s
.PHONY : error.c.s

misc.o: misc.c.o

.PHONY : misc.o

# target to build an object file
misc.c.o:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/misc.c.o
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/misc.c.o
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/misc.c.o
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/misc.c.o
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/misc.c.o
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/misc.c.o
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/misc.c.o
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/misc.c.o
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/misc.c.o
.PHONY : misc.c.o

misc.i: misc.c.i

.PHONY : misc.i

# target to preprocess a source file
misc.c.i:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/misc.c.i
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/misc.c.i
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/misc.c.i
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/misc.c.i
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/misc.c.i
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/misc.c.i
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/misc.c.i
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/misc.c.i
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/misc.c.i
.PHONY : misc.c.i

misc.s: misc.c.s

.PHONY : misc.s

# target to generate assembly for a file
misc.c.s:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/misc.c.s
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/misc.c.s
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/misc.c.s
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/misc.c.s
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/misc.c.s
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/misc.c.s
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/misc.c.s
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/misc.c.s
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/misc.c.s
.PHONY : misc.c.s

version.o: version.c.o

.PHONY : version.o

# target to build an object file
version.c.o:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/version.c.o
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/version.c.o
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/version.c.o
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/version.c.o
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/version.c.o
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/version.c.o
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/version.c.o
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/version.c.o
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/version.c.o
.PHONY : version.c.o

version.i: version.c.i

.PHONY : version.i

# target to preprocess a source file
version.c.i:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/version.c.i
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/version.c.i
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/version.c.i
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/version.c.i
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/version.c.i
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/version.c.i
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/version.c.i
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/version.c.i
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/version.c.i
.PHONY : version.c.i

version.s: version.c.s

.PHONY : version.s

# target to generate assembly for a file
version.c.s:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/version.c.s
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/version.c.s
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/version.c.s
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/version.c.s
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/version.c.s
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/version.c.s
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/version.c.s
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/version.c.s
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/version.c.s
.PHONY : version.c.s

zfile.o: zfile.c.o

.PHONY : zfile.o

# target to build an object file
zfile.c.o:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/zfile.c.o
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/zfile.c.o
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/zfile.c.o
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/zfile.c.o
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/zfile.c.o
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/zfile.c.o
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/zfile.c.o
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/zfile.c.o
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/zfile.c.o
.PHONY : zfile.c.o

zfile.i: zfile.c.i

.PHONY : zfile.i

# target to preprocess a source file
zfile.c.i:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/zfile.c.i
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/zfile.c.i
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/zfile.c.i
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/zfile.c.i
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/zfile.c.i
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/zfile.c.i
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/zfile.c.i
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/zfile.c.i
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/zfile.c.i
.PHONY : zfile.c.i

zfile.s: zfile.c.s

.PHONY : zfile.s

# target to generate assembly for a file
zfile.c.s:
	$(MAKE) -f CMakeFiles/adflist.dir/build.make CMakeFiles/adflist.dir/zfile.c.s
	$(MAKE) -f CMakeFiles/adfinfo.dir/build.make CMakeFiles/adfinfo.dir/zfile.c.s
	$(MAKE) -f CMakeFiles/adfdump.dir/build.make CMakeFiles/adfdump.dir/zfile.c.s
	$(MAKE) -f CMakeFiles/adfcreate.dir/build.make CMakeFiles/adfcreate.dir/zfile.c.s
	$(MAKE) -f CMakeFiles/adfmakedir.dir/build.make CMakeFiles/adfmakedir.dir/zfile.c.s
	$(MAKE) -f CMakeFiles/adfextract.dir/build.make CMakeFiles/adfextract.dir/zfile.c.s
	$(MAKE) -f CMakeFiles/adfcopy.dir/build.make CMakeFiles/adfcopy.dir/zfile.c.s
	$(MAKE) -f CMakeFiles/adfdelete.dir/build.make CMakeFiles/adfdelete.dir/zfile.c.s
	$(MAKE) -f CMakeFiles/adfinstall.dir/build.make CMakeFiles/adfinstall.dir/zfile.c.s
.PHONY : zfile.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... adflist"
	@echo "... adfinfo"
	@echo "... adfdump"
	@echo "... adfcreate"
	@echo "... rebuild_cache"
	@echo "... adfmakedir"
	@echo "... adfextract"
	@echo "... adfcopy"
	@echo "... adfdelete"
	@echo "... adfinstall"
	@echo "... adf"
	@echo "... adfcopy.o"
	@echo "... adfcopy.i"
	@echo "... adfcopy.s"
	@echo "... adfcreate.o"
	@echo "... adfcreate.i"
	@echo "... adfcreate.s"
	@echo "... adfdelete.o"
	@echo "... adfdelete.i"
	@echo "... adfdelete.s"
	@echo "... adfdump.o"
	@echo "... adfdump.i"
	@echo "... adfdump.s"
	@echo "... adfextract.o"
	@echo "... adfextract.i"
	@echo "... adfextract.s"
	@echo "... adfinfo.o"
	@echo "... adfinfo.i"
	@echo "... adfinfo.s"
	@echo "... adfinstall.o"
	@echo "... adfinstall.i"
	@echo "... adfinstall.s"
	@echo "... adflist.o"
	@echo "... adflist.i"
	@echo "... adflist.s"
	@echo "... adfmakedir.o"
	@echo "... adfmakedir.i"
	@echo "... adfmakedir.s"
	@echo "... bootblocks.o"
	@echo "... bootblocks.i"
	@echo "... bootblocks.s"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... misc.o"
	@echo "... misc.i"
	@echo "... misc.s"
	@echo "... version.o"
	@echo "... version.i"
	@echo "... version.s"
	@echo "... zfile.o"
	@echo "... zfile.i"
	@echo "... zfile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

